# Python Basics

## Slicing

http://cs231n.github.io/python-numpy-tutorial/  
this part uses the python2  
if you want to use python3,  
change the print format as  
print A --> print(A)

In [1]:
%%python2
nums = range(5)    # range is a built-in function that creates a list of integers
print nums         # Prints "[0, 1, 2, 3, 4]"
print nums[2:4]    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print nums[2:]     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print nums[:2]     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print nums[:]      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print nums[:-1]    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print nums         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


## Indexing, Slicing, Iterating
http://slides.com/wigging/numpy#/9
- Arrays can be indexed, sliced, iterated much like lists and other sequence types in Python
- As with Python lists, slicing in NumPy can be  accomplished with the colon ( : ) syntax
- Colon instances ( : ) can be replaced with dots ( ... )


In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
# array([1, 2, 3, 4, 5])

In [4]:
a[1:3]
# array([2, 3])

array([2, 3])

In [5]:
a[-1]
# 5

5

In [6]:
a[0:2] = 9

In [7]:
a
# array([9, 9, 3, 4, 5])

array([9, 9, 3, 4, 5])

In [8]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])

In [9]:
b[:, 1]
# array([ 2,  6, 10])

array([ 2,  6, 10])

In [10]:
b[-1]
# array([ 9, 10, 11, 12])

array([ 9, 10, 11, 12])

In [11]:
b[-1, :]
# array([ 9, 10, 11, 12])

array([ 9, 10, 11, 12])

In [12]:
b[-1, ...]
# array([ 9, 10, 11, 12])

array([ 9, 10, 11, 12])

In [13]:
b[0:2, :]
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Loading data from file

In [14]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777) # for reproducibility

**slice the data by spliting with ',' 
change data type as np.float32**

In [15]:
xy = np.loadtxt('data-01-test-score.csv',delimiter=',',dtype=np.float32)

**take care of the slicing part**

In [16]:
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]  

print(x_data.shape,'\n', x_data,'\n',len(x_data))
print(y_data.shape,'\n', y_data,'\n',len(y_data))


(25, 3) 
 [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 
 25
(25, 1) 
 [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]] 
 25


In [17]:
# placehiolders for a tensor that will be always fed
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name="weight")
b = tf.Variable(tf.random_normal([1]),name="bias")

# Hypothsis 
hypothsis = tf.matmul(X,W)+b
# simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothsis - Y))

# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


In [18]:
# Launch the graph in a Session
sess = tf.Session()
# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val,hy_val,_ = sess.run([cost,hypothsis,train],
                feed_dict= {X:x_data,Y:y_data})
    if step%10==0:
        print(step,"Cost:",sess.run(tf.transpose(cost_val)),"\nPrediction:\n",hy_val)
# Ask my Score        
print("your score will be",
      sess.run(hypothsis,feed_dict={X:[[100,70,101]]}))
print("other scores will be",
     sess.run(hypothsis,feed_dict={X:[[60,70,100],[90,100,80]]}))

0 Cost: 21027.0 
Prediction:
 [[ 22.04806328]
 [ 21.61978722]
 [ 24.09669304]
 [ 22.29300499]
 [ 18.6339016 ]
 [  7.2669735 ]
 [ 12.33102989]
 [  3.15051103]
 [ 14.34794426]
 [  4.25342369]
 [ 14.48570824]
 [ 10.67806816]
 [ 28.80463982]
 [ 29.29880333]
 [ 11.23783684]
 [ 18.6465435 ]
 [ 31.18945122]
 [ 13.34466362]
 [ 28.84174156]
 [ 25.66280937]
 [ 15.08476067]
 [ 16.79836845]
 [ 15.92455101]
 [ 31.36112022]
 [ 24.98636436]]
10 Cost: 95.9763 
Prediction:
 [[ 157.11062622]
 [ 183.99281311]
 [ 184.0630188 ]
 [ 196.5291748 ]
 [ 142.46273804]
 [  98.59757233]
 [ 142.77235413]
 [  99.87779999]
 [ 166.13175964]
 [ 144.89149475]
 [ 140.14994812]
 [ 134.61138916]
 [ 194.0514679 ]
 [ 166.64041138]
 [ 142.2870636 ]
 [ 183.4329834 ]
 [ 161.97666931]
 [ 169.89073181]
 [ 186.37145996]
 [ 166.61376953]
 [ 168.04634094]
 [ 169.14367676]
 [ 161.75204468]
 [ 167.48861694]
 [ 193.25117493]]
20 Cost: 94.2573 
Prediction:
 [[ 158.01502991]
 [ 185.11975098]
 [ 185.15112305]
 [ 197.73497009]
 [ 143.315002

# Whole coding of ***Loading data from file***

And I add an **timer** into this part then we can compare the **speed** processing with the coding which use the **train-batch-version** to read the data file.

In [19]:
import tensorflow as tf

In [20]:
import numpy as np
import time
 
start = time.clock()

tf.set_random_seed(777) # for reproducibility
xy = np.loadtxt('data-01-test-score.csv',delimiter=',',dtype=np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]  ##### error

# placehiolders for a tensor that will be always fed
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name="weight")
b = tf.Variable(tf.random_normal([1]),name="bias")

# Hypothsis 
hypothsis = tf.matmul(X,W)+b
# simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothsis - Y))

# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a Session
sess = tf.Session()
# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val,hy_val,_ = sess.run([cost,hypothsis,train],
                feed_dict= {X:x_data,Y:y_data})
    if step%10==0:
        print(step,"Cost:",sess.run(tf.transpose(cost_val)),"\nPrediction:\n",hy_val)
# Ask my Score        
print("your score will be",
      sess.run(hypothsis,feed_dict={X:[[100,70,101]]}))
print("other scores will be",
     sess.run(hypothsis,feed_dict={X:[[60,70,100],[90,100,80]]}))

elapsed = (time.clock() - start)
print("Time used:",elapsed)

0 Cost: 41891.1 
Prediction:
 [[-31.50125694]
 [-49.37805557]
 [-42.51730728]
 [-49.07924652]
 [-38.17271042]
 [-33.65266037]
 [-37.54118347]
 [-28.64108849]
 [-52.14752579]
 [-55.38408279]
 [-36.75141907]
 [-42.34530258]
 [-41.32451248]
 [-31.14841652]
 [-39.73122025]
 [-51.67230606]
 [-29.87055016]
 [-44.18819046]
 [-37.1820755 ]
 [-32.49848175]
 [-44.73748398]
 [-48.25558472]
 [-40.88571167]
 [-25.62674141]
 [-48.09203339]]
10 Cost: 76.4526 
Prediction:
 [[ 159.40538025]
 [ 180.13052368]
 [ 183.5907135 ]
 [ 197.18710327]
 [ 136.86450195]
 [  95.42879486]
 [ 146.80804443]
 [ 108.03691864]
 [ 162.37908936]
 [ 143.36357117]
 [ 140.8583374 ]
 [ 132.8132782 ]
 [ 192.2593689 ]
 [ 163.00689697]
 [ 145.47576904]
 [ 181.23641968]
 [ 155.0330658 ]
 [ 177.04690552]
 [ 185.49526978]
 [ 166.74176025]
 [ 171.44311523]
 [ 167.06774902]
 [ 165.21566772]
 [ 166.81298828]
 [ 189.74993896]]
20 Cost: 73.8529 
Prediction:
 [[ 160.68937683]
 [ 181.72958374]
 [ 185.13607788]
 [ 198.88778687]
 [ 138.083343