In [1]:
# http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/
# http://learningtensorflow.com/index.html
# http://suriyadeepan.github.io/2016-12-31-practical-seq2seq/

import tensorflow as tf
import numpy as np
from tensorflow.contrib import rnn
import pprint
pp = pprint.PrettyPrinter(indent=4)

In [2]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

# One cell RNN input_dim (3) -> output_dim (5)
hidden_size = 5
cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
print(cell.output_size, cell.state_size)

x_data = np.array([[[1, 2, 3]]], dtype=np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())
sess.close()

5 5
array([[[ 0.67206371,  0.65352339,  0.98913652,  0.96597087, -0.80571556]]], dtype=float32)


In [3]:
tf.reset_default_graph()
sess = tf.InteractiveSession()

# One cell RNN input_dim (3) -> output_dim (5). sequence: 2
hidden_size = 5
cell = tf.contrib.rnn.BasicRNNCell(num_units=hidden_size)
x_data = np.array([[[1, 2, 3],
                    [4, 5, 6]]], dtype=np.float32)
outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())
sess.close()

array([[[-0.98075986,  0.90735137, -0.88604391,  0.68126518,  0.16285048],
        [-0.99993587,  0.99957901, -0.99994498,  0.99769789, -0.28474009]]], dtype=float32)


In [4]:
tf.reset_default_graph()
sess = tf.InteractiveSession()
# One cell RNN input_dim (3) -> output_dim (5). sequence: 2
cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
x_data = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]],

                   [[13, 14, 15],
                    [16, 17, 18]], ], dtype=np.float32)
outputs, _states = tf.nn.dynamic_rnn(
    cell, x_data, sequence_length=[1,2,1], dtype=tf.float32)
sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())
sess.close()

array([[[  3.96448374e-02,   3.68381441e-01,   3.53435464e-02,
          -3.15800607e-02,  -5.11811912e-01],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00]],

       [[ -1.51261678e-02,   6.56784832e-01,   9.81306424e-04,
          -1.28108586e-04,  -7.60237753e-01],
        [ -1.32748885e-02,   7.33923078e-01,   8.47485935e-05,
          -6.61454324e-05,  -8.26280653e-01]],

       [[ -7.92227965e-03,   7.35501111e-01,   7.61512592e-06,
          -3.26206532e-07,  -7.61585116e-01],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00]]], dtype=float32)


In [5]:
tf.reset_default_graph()
sess = tf.InteractiveSession()
# One cell RNN input_dim (3) -> output_dim (5). sequence: 2

batch_size = 3
cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
initial_state = cell.zero_state(batch_size, tf.float32)

x_data = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]],

                   [[13, 14, 15],
                    [16, 17, 18]], ], dtype=np.float32)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data,
                                     initial_state=initial_state, dtype=tf.float32)
sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())
sess.close()

array([[[ -1.05524763e-01,  -6.84732646e-02,   2.12972298e-01,
           5.02873659e-02,  -1.36999935e-02],
        [ -3.27386558e-02,  -2.84101833e-02,   5.14315188e-01,
           1.62311733e-01,  -1.27450482e-03]],

       [[ -5.97264525e-03,  -1.34854077e-03,   3.82874131e-01,
           6.76370859e-02,   1.54392375e-03],
        [ -1.05463120e-03,  -1.19260148e-04,   6.51077747e-01,
           3.96581888e-02,   6.61409809e-04]],

       [[ -1.87620099e-04,  -9.06134119e-06,   4.20798212e-01,
           8.92801397e-03,   5.10805585e-05],
        [ -3.30030489e-05,  -6.07899210e-07,   7.00302601e-01,
           3.74964345e-03,   2.02135179e-05]]], dtype=float32)


In [6]:
tf.reset_default_graph()
sess = tf.InteractiveSession()
# Create input data
x_data = np.arange(24, dtype=np.float32).reshape(2, 4, 3)
pp.pprint(x_data)  # batch, sequence_length, input size

array([[[  0.,   1.,   2.],
        [  3.,   4.,   5.],
        [  6.,   7.,   8.],
        [  9.,  10.,  11.]],

       [[ 12.,  13.,  14.],
        [ 15.,  16.,  17.],
        [ 18.,  19.,  20.],
        [ 21.,  22.,  23.]]], dtype=float32)


In [7]:
# Make rnn
cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
cell = rnn.MultiRNNCell([cell] * 3, state_is_tuple=True)

# rnn in/out
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
print("dynamic rnn: ", outputs)
sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())  # batch size, unrolling (time), hidden_size

dynamic rnn:  Tensor("rnn/transpose:0", shape=(2, 4, 5), dtype=float32)
array([[[-0.00136516, -0.00125313,  0.00230622, -0.0001321 , -0.00069181],
        [-0.00264667, -0.0035607 ,  0.00355315,  0.00374622, -0.00570776],
        [-0.00365446, -0.00849542,  0.00445551,  0.01487348, -0.01432846],
        [-0.00639565, -0.01795833,  0.00789715,  0.03302194, -0.02343089]],

       [[ 0.00017107, -0.00672182,  0.00344312,  0.01485206, -0.00282333],
        [-0.00027203, -0.02135739,  0.00982386,  0.04159984, -0.00740837],
        [-0.00281457, -0.04195821,  0.01899138,  0.0737903 , -0.01185923],
        [-0.00803155, -0.06594773,  0.03017751,  0.10696599, -0.015134  ]]], dtype=float32)


In [8]:
cell = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32,
                                     sequence_length=[1, 2])
print("dynamic rnn: ", outputs)
sess.run(tf.global_variables_initializer())
pp.pprint(outputs.eval())  # batch size, unrolling (time), hidden_size
sess.close()

dynamic rnn:  Tensor("rnn_1/transpose:0", shape=(2, 4, 5), dtype=float32)
array([[[-0.06643986,  0.04374039, -0.00924233,  0.10854677,  0.15136461],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],

       [[-0.02763105,  0.00894361,  0.0041775 ,  0.15297839,  0.0774397 ],
        [-0.01809281,  0.01035907,  0.00145653,  0.1227403 ,  0.12365469],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]]], dtype=float32)


In [9]:
tf.reset_default_graph()
sess = tf.InteractiveSession()
# bi-directional rnn
cell_fw = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)
cell_bw = rnn.BasicLSTMCell(num_units=5, state_is_tuple=True)

outputs, states = tf.nn.bidirectional_dynamic_rnn(cell_fw, cell_bw, x_data,
                                                  sequence_length=[2, 3],
                                                  dtype=tf.float32)

sess.run(tf.global_variables_initializer())
pp.pprint(sess.run(outputs))
pp.pprint(sess.run(states))

(   array([[[  1.35668442e-01,  -7.58908018e-02,   3.20433378e-02,
           1.11595333e-01,   6.78025186e-02],
        [  8.42873529e-02,  -1.22437380e-01,   4.90654051e-01,
           1.97011560e-01,   4.53755483e-02],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00]],

       [[  6.36829063e-05,  -2.89044157e-03,   7.53046095e-01,
           1.19148783e-01,  -3.34614958e-03],
        [  8.83828125e-06,  -2.62478366e-03,   7.67140090e-01,
           1.16692930e-01,  -1.31387636e-03],
        [  9.61140245e-07,  -1.66672072e-03,   7.64704943e-01,
           8.83861855e-02,  -6.31130999e-04],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00,   0.00000000e+00]]], dtype=float32),
    array([[[  3.71433616e-01,  -8.10414627e-02,   2.56676912e-01,
          -1.36370853e-01,   9.004388

In [10]:
# Broadcasting based softmax
softmax_w = np.arange(12, dtype=np.float32).reshape(4, 3)
outputs = x_data * softmax_w
pp.pprint(softmax_w)
pp.pprint(outputs)
outputs = x_data * softmax_w + [1, 2, 3]
pp.pprint(outputs)

array([[  0.,   1.,   2.],
       [  3.,   4.,   5.],
       [  6.,   7.,   8.],
       [  9.,  10.,  11.]], dtype=float32)
array([[[   0.,    1.,    4.],
        [   9.,   16.,   25.],
        [  36.,   49.,   64.],
        [  81.,  100.,  121.]],

       [[   0.,   13.,   28.],
        [  45.,   64.,   85.],
        [ 108.,  133.,  160.],
        [ 189.,  220.,  253.]]], dtype=float32)
array([[[   1.,    3.,    7.],
        [  10.,   18.,   28.],
        [  37.,   51.,   67.],
        [  82.,  102.,  124.]],

       [[   1.,   15.,   31.],
        [  46.,   66.,   88.],
        [ 109.,  135.,  163.],
        [ 190.,  222.,  256.]]])


In [11]:
# [batch_size, sequence_length, emb_dim ]
prediction1 = tf.constant([[[0, 1], [0, 1], [0, 1]]], dtype=tf.float32)
prediction2 = tf.constant([[[1, 0], [1, 0], [1, 0]]], dtype=tf.float32)
prediction3 = tf.constant([[[0, 1], [1, 0], [0, 1]]], dtype=tf.float32)

# [batch_size, sequence_length]
y_data = tf.constant([[1, 1, 1]])

# [batch_size * sequence_length]
weights = tf.constant([[1, 1, 1]], dtype=tf.float32)

sequence_loss1 = tf.contrib.seq2seq.sequence_loss(prediction1, y_data, weights)
sequence_loss2 = tf.contrib.seq2seq.sequence_loss(prediction2, y_data, weights)
sequence_loss3 = tf.contrib.seq2seq.sequence_loss(prediction3, y_data, weights)

sess.run(tf.global_variables_initializer())
print("Loss1: ", sequence_loss1.eval(),
      "Loss2: ", sequence_loss2.eval(),
      "Loss3: ", sequence_loss3.eval())

Loss1:  0.313262 Loss2:  1.31326 Loss3:  0.646595
